"""Player portrait pipeline: cutout → photo → pre-rendered face SVG → monogram roundel.

Cutouts live at scripts/portraits/rendered/{pid}.png with a manifest.json mapping pid
to the photo URL each was cut from (generated by the one-off
``python3 scripts/cutout_portraits.py <export>``). They are the same photo as
``imgURL`` with a flat studio backdrop flood-filled to transparent, so a headshot stops
rendering as a bright disc on a dark card. Only photos whose backdrop is actually flat
get one -- an action shot cannot be cut from a crowd -- so the pool is a mix of cutouts
and hot-linked originals by design. ``emit_portraits`` copies them to
``<out>/assets/portraits/``, which is build output only.


Source face SVGs live at scripts/faces/rendered/{pid}.svg (generated by the
one-off ``node scripts/faces/render.mjs``) with sentinel jersey colors
(#F00BA1/#F00BA2/#F00BA3) plus a manifest.json alongside. At build time,
``emit_faces`` string-swaps the sentinels for the player's current team
identity colors and writes the recolored copies to ``<out>/assets/faces/`` —
``assets/faces/`` in the deployed site is build output only.

``portrait_html`` renders the fallback chain for pages: hotlinked photo
(``imgURL``) when present, else the recolored face SVG when the player owns one,
else an inline monogram roundel. Never a broken image.

A rendered SVG is only ever used for a player who still carries a ``face`` in
the export being built — see ``has_face``. pids are league-local, so a manifest
rendered from a different league would otherwise paint one player's portrait
onto whoever happens to hold that pid now.
"""

from __future__ import annotations

import functools
import json
from pathlib import Path
from urllib.parse import quote
from typing import Any, Iterable, Union

from .core import esc, initials, player_name

# Directory holding the sentinel-colored source SVGs + manifest.json.
RENDERED_DIR = Path(__file__).resolve().parent.parent / "faces" / "rendered"

# Directory holding the background-stripped photo cutouts + manifest.json.
CUTOUT_DIR = Path(__file__).resolve().parent.parent / "portraits" / "rendered"

# Sentinel hexes render.mjs bakes into every source SVG, in swap order:
# [primary, secondary, on_primary]. manifest.json records the exact casing
# facesjs emitted; these are the fallback if the manifest omits them.
SENTINELS = ("#F00BA1", "#F00BA2", "#F00BA3")

# Neutral grays for players without a team identity (free agents, retired):
# [primary, secondary, on_primary].
FA_COLORS = ("#3a4048", "#8a93a0", "#e8ecf1")

DEFAULT_PORTRAIT_SIZE = 72


def _identity():
    """Late import so this module stays importable on its own (identity.py
    lands in the same phase); also gives tests a single seam to stub."""
    from . import identity

    return identity


@functools.lru_cache(maxsize=None)
def load_face_manifest() -> dict[str, Any]:
    """Load scripts/faces/rendered/manifest.json (cached).

    Returns ``{"pids": frozenset[int], "sentinels": tuple[str, str, str]}``.
    Missing or unreadable manifest → empty pid set (portraits fall through to
    monograms instead of breaking the build).
    """
    path = RENDERED_DIR / "manifest.json"
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"pids": frozenset(), "sentinels": SENTINELS}
    pids = frozenset(p for p in raw.get("pids", []) if isinstance(p, int))
    sentinels = raw.get("sentinels") or []
    if not (isinstance(sentinels, list) and len(sentinels) == len(SENTINELS)):
        sentinels = list(SENTINELS)
    return {"pids": pids, "sentinels": tuple(str(s) for s in sentinels)}


@functools.lru_cache(maxsize=None)
def load_cutout_manifest() -> dict[int, str]:
    """Load scripts/portraits/rendered/manifest.json (cached): ``{pid: source URL}``.

    Missing or unreadable → no cutouts, and every portrait falls back to hot-linking
    the original photo. A cosmetic asset must never be able to break the build.
    """
    try:
        raw = json.loads((CUTOUT_DIR / "manifest.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    if not isinstance(raw, dict):
        return {}
    out: dict[int, str] = {}
    for pid, url in raw.items():
        try:
            out[int(pid)] = str(url)
        except (TypeError, ValueError):
            continue
    return out


def cutout_src(player: Union[dict[str, Any], None], root: str = "") -> Union[str, None]:
    """Path to this player's cutout, or None.

    The manifest records the photo each cutout was made from, and the player has to
    still carry that exact URL. pids are league-local and photos get swapped, so
    without that check a manifest left over from another pool would hang a stranger's
    face on whoever holds the pid now -- the same trap ``has_face`` guards.
    """
    if not isinstance(player, dict):
        return None
    pid = player.get("pid")
    if not isinstance(pid, int):
        return None
    source = load_cutout_manifest().get(pid)
    if not source or source != (player.get("imgURL") or "").strip():
        return None
    return f"{root}assets/portraits/{pid}.png"


def emit_portraits(out_dir: Union[str, Path], players: Union[dict[int, dict[str, Any]], Iterable[dict[str, Any]]]) -> None:
    """Copy every cutout this export can actually reach to ``<out>/assets/portraits/``.

    Gated by ``cutout_src`` so the output never carries an image no page links to,
    and byte-identical across rebuilds — unchanged files are not rewritten.
    """
    if isinstance(players, dict):
        players_by_pid = players
    else:
        players_by_pid = {p.get("pid"): p for p in players if isinstance(p, dict)}

    dest = Path(out_dir) / "assets" / "portraits"
    dest.mkdir(parents=True, exist_ok=True)
    for pid in sorted(load_cutout_manifest()):
        if cutout_src(players_by_pid.get(pid)) is None:
            continue
        try:
            data = (CUTOUT_DIR / f"{pid}.png").read_bytes()
        except OSError:
            continue  # manifest/file drift; skip rather than break the build
        target = dest / f"{pid}.png"
        try:
            if target.read_bytes() == data:
                continue
        except OSError:
            pass
        target.write_bytes(data)


def has_face(player: Union[dict[str, Any], None]) -> bool:
    """True when this player owns the rendered ``{pid}.svg``, not merely shares its pid.

    render.mjs only renders players carrying a non-empty ``face`` object, so a
    player without one in the current export cannot be the player that SVG was
    drawn for — the manifest is left over from another league. Requiring both
    keeps a stale manifest from putting a stranger's portrait on a real player;
    faces reappear on their own once render.mjs is re-run for this league.
    """
    if not isinstance(player, dict):
        return False
    pid = player.get("pid")
    if not isinstance(pid, int) or pid not in load_face_manifest()["pids"]:
        return False
    face = player.get("face")
    return isinstance(face, dict) and bool(face)


def _face_colors(player: Union[dict[str, Any], None]) -> tuple[str, str, str]:
    """Resolve [primary, secondary, on_primary] for a player's current team;
    free agents / retired / unknown teams get neutral grays."""
    tid = (player or {}).get("tid")
    if isinstance(tid, int) and tid >= 0:
        team = _identity().TEAM_IDENTITY.get(tid)
        if team:
            return (str(team["primary"]), str(team["secondary"]), str(team["on_primary"]))
    return FA_COLORS


def _write_if_changed(path: Path, content: str) -> bool:
    try:
        if path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        pass
    path.write_text(content, encoding="utf-8")
    return True


def emit_faces(out_dir: Union[str, Path], players: Union[dict[int, dict[str, Any]], Iterable[dict[str, Any]]]) -> None:
    """Write recolored face SVGs to ``<out_dir>/assets/faces/{pid}.svg`` for
    every player in this export that owns one.

    ``players`` is either a pid→player mapping or an iterable of player dicts
    (each carrying ``pid``/``tid``). Sentinels are literally string-replaced
    with the player's current team identity colors (free agents → neutral
    grays). Deterministic: same inputs → identical bytes; unchanged files are
    not rewritten. Emission uses the same ``has_face`` gate the pages do, so the
    output never carries a face no page can reach.
    """
    if isinstance(players, dict):
        players_by_pid = players
    else:
        players_by_pid = {p.get("pid"): p for p in players if isinstance(p, dict)}

    manifest = load_face_manifest()
    sentinels = manifest["sentinels"]
    dest = Path(out_dir) / "assets" / "faces"
    dest.mkdir(parents=True, exist_ok=True)

    for pid in sorted(manifest["pids"]):
        player = players_by_pid.get(pid)
        if not has_face(player):
            continue
        src = RENDERED_DIR / f"{pid}.svg"
        try:
            svg = src.read_text(encoding="utf-8")
        except OSError:
            continue  # manifest/file drift; skip rather than break the build
        colors = _face_colors(player)
        for sentinel, color in zip(sentinels, colors):
            svg = svg.replace(sentinel, color)
        _write_if_changed(dest / f"{pid}.svg", svg)


def portrait_html(
    player: dict[str, Any],
    cls: str = "portrait",
    root: str = "",
    size: int = DEFAULT_PORTRAIT_SIZE,
) -> str:
    """Portrait <img>/monogram for a player: cutout → photo → face SVG → monogram.

    The cutout is the same photo with its studio backdrop removed, so it is preferred
    wherever one exists; players whose photo could not be cut keep hot-linking it.

    Never renders a broken image: photos get an ``onerror`` hook that adds a
    ``portrait-broken`` class and falls back to the face SVG (when one exists)
    or hides the bitmap; players with neither photo nor face get an inline
    monogram roundel.
    """
    name = player_name(player)
    pid = player.get("pid")
    face_src = f"{root}assets/faces/{pid}.svg" if has_face(player) else None

    img = cutout_src(player, root) or (player.get("imgURL") or "")
    if isinstance(img, str) and img.strip():
        if face_src:
            onerror = f"this.onerror=null;this.classList.add('portrait-broken');this.src='{face_src}'"
        else:
            # Dead photo with no face: swap in the monogram markup so the slot
            # never renders as an empty ring.
            mono_markup = _monogram_span(player, cls, name)
            onerror = (
                "this.onerror=null;"
                f"this.outerHTML=decodeURIComponent('{quote(mono_markup)}')"
            )
        return (
            f'<img class="{esc(cls)}" src="{esc(img.strip())}" alt="{esc(name)}"'
            f' loading="lazy" decoding="async" width="{int(size)}" height="{int(size)}"'
            f' onerror="{onerror}">'
        )

    if face_src:
        return (
            f'<img class="{esc(cls)}" src="{face_src}" alt="{esc(name)}"'
            f' loading="lazy" decoding="async" width="{int(size)}" height="{int(size)}">'
        )

    return _monogram_span(player, cls, name)


def _monogram_span(player: dict[str, Any], cls: str, name: str) -> str:
    mono = _identity().monogram_svg(
        initials(player),
        player.get("tid"),
        jersey_number=player.get("jerseyNumber"),
    )
    return f'<span class="{esc(cls)} portrait-monogram" role="img" aria-label="{esc(name)}">{mono}</span>'
