"""Tests for the skill-badge rule (scripts/smp/core.py: SKILL_RULES / rating_skills).

The SMP II pool comes from a real-player database that carries no ``skills`` on its
ratings rows, so the badges have to be recomputed. The rule is checked against the
only ground truth available: the archived SMP I exports, whose ratings BBGM itself
labelled. Only rows from seasons the league actually played are used — rows for
earlier seasons are imported real-player histories whose badges were computed by
something other than this engine, and they disagree about 10% of the time.
"""

import glob
import json
import os
import sys
import unittest

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
_SCRIPTS = os.path.join(_REPO, "scripts")
if _SCRIPTS not in sys.path:
    sys.path.insert(0, _SCRIPTS)
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from current_export import current_export_path  # noqa: E402

from smp.core import SKILL_LABELS, SKILL_RULES, rating_skills  # noqa: E402

_ARCHIVE = os.path.join(_REPO, "league-data", "smp1", "*.json")
_EXPORT = current_export_path()

# SMP I began in 2026: rows from 2027 on were generated by BBGM inside the league.
_LEAGUE_FIRST_GENERATED_SEASON = 2027


def _labelled_rows():
    """BBGM-labelled ratings rows from seasons SMP I actually simulated."""
    rows = []
    for path in sorted(glob.glob(_ARCHIVE)):
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        if not isinstance(data, dict):
            continue  # odds_history.json is a list, not an export
        for player in data.get("players", []):
            for rating in player.get("ratings", []):
                if (isinstance(rating.get("skills"), list)
                        and rating.get("season", 0) >= _LEAGUE_FIRST_GENERATED_SEASON):
                    rows.append(rating)
    return rows


class TestSkillRuleAgainstBBGM(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.rows = _labelled_rows()

    def test_the_archive_actually_has_labels_to_check(self):
        # Guard the guard: an empty corpus would make every assertion below vacuous.
        self.assertGreater(len(self.rows), 1000)
        self.assertTrue(any(r["skills"] for r in self.rows))

    def test_reproduces_every_badge_bbgm_assigned(self):
        mismatches = []
        for rating in self.rows:
            expected = sorted(rating["skills"])
            # Drop the exported list so the rule is exercised, not echoed.
            got = sorted(rating_skills({k: v for k, v in rating.items() if k != "skills"}))
            if got != expected:
                mismatches.append((expected, got))
        self.assertEqual(mismatches[:5], [], f"{len(mismatches)} of {len(self.rows)} rows disagree")

    def test_every_badge_code_appears_in_the_corpus(self):
        seen = set()
        for rating in self.rows:
            seen.update(rating["skills"])
        self.assertEqual(seen, set(SKILL_RULES))


class TestRatingSkills(unittest.TestCase):
    def test_exported_skills_win_over_the_rule(self):
        # BBGM is the authority on rows it labelled itself.
        self.assertEqual(rating_skills({"skills": ["3"], "tp": 0, "oiq": 0}), ["3"])
        self.assertEqual(rating_skills({"skills": []}), [])

    def test_codes_are_ordered_and_labelled(self):
        codes = list(SKILL_RULES)
        self.assertEqual(codes, list(SKILL_LABELS))
        self.assertEqual(rating_skills({"skills": ["V", "A"]}), ["V", "A"])  # export order kept

    def test_missing_subratings_never_raise(self):
        self.assertEqual(rating_skills({}), [])
        self.assertEqual(rating_skills({"tp": 99}), [])  # oiq missing -> "3" can't be judged

    def test_derived_badges_match_the_games_own_for_every_rostered_player(self):
        """Our rules reproduce Basketball GM's, checked against the live export.

        This used to pin one player's badges to a literal list. That rots on
        contact with the league: Carmelo Anthony tore a meniscus on opening day,
        the injury penalty took his ratings down, and A/Di/Po/V legitimately
        became Po/V — a green test turning red over a knee, not over a bug. The
        invariant worth holding is that our derivation agrees with the skills the
        game itself stamped on the same ratings row, for everyone.
        """
        with open(_EXPORT, encoding="utf-8") as fh:
            data = json.load(fh)
        rostered = [p for p in data["players"] if isinstance(p.get("tid"), int) and p["tid"] >= 0]
        self.assertGreater(len(rostered), 0)
        checked = 0
        for player in rostered:
            row = player["ratings"][-1]
            if "skills" not in row:
                continue
            derived = rating_skills({k: v for k, v in row.items() if k != "skills"})
            with self.subTest(player=f'{player["firstName"]} {player["lastName"]}'):
                self.assertEqual(derived, list(row["skills"]))
            checked += 1
        self.assertGreater(checked, 100)


if __name__ == "__main__":
    unittest.main()
